# Generated by Django 5.2.7 on 2025-10-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Anúncio')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço (€)')),
                ('endereco', models.CharField(max_length=255, verbose_name='Morada Completa')),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('LOTE', 'Lote')], default='CASA', max_length=4, verbose_name='Tipo de Imóvel')),
                ('esta_a_venda', models.BooleanField(default=True, verbose_name='Disponível para Venda')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
