# Generated by Django 5.2.7 on 2025-10-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/', verbose_name='Imagem Principal'),
        ),
    ]
