# Generated by Django 5.2.7 on 2025-10-29 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_imagem_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/%Y/%m/%d/', verbose_name='Foto Adicional')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
            },
        ),
    ]
